---
- debug: msg="##### Wait for async tasks to finish DEPLOYMENT {{ lookup('pipe', 'date +%Y%m%d-%H%M%S') }}"
- name: CAT result check (Check coroutine)
  async_status:
    jid: "{{ cat_install.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30

- name: REP result check (Check coroutine)
  async_status:
    jid: "{{ rep_install.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30

- name: PM result check (Check coroutine)
  async_status:
    jid: "{{ pm_install.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30