---
# HARD RESET
# cleaning databases
# - import_tasks: clean_db.yml
#   when: (clean == 'true')

# deploy MongoDB (NoSQL) database engine
# deploy RabbitMQ message bus

- import_tasks: emulator.yml
  when: (component == 'broker') or 
        (component == 'mano-framework') or
        (component == 'all')

- import_tasks: rabbitmq.yml
  when: (component == 'broker') or 
        (component == 'mano-framework') or
        (component == 'all')

- import_tasks: mongo.yml
  when: (component == 'database') or 
        (component == 'mano-framework') or
        (component == 'all')

## Deploying Mano Components
- import_tasks: finish_rabbitmq_mongo.yaml
  when: (component == 'mano-framework') or
        (component == 'placement-plugin') or
        (component == 'all')

# deploy Catalogues
- import_tasks: cat.yml
  when: (component == 'catalogues') or
        (component == 'mano-framework') or
        (component == 'all')

# deploy Repositories
- import_tasks: rep.yml
  when: (component == 'repositories') or
        (component == 'mano-framework') or
        (component == 'all')

# deploy PluginManager of MANO framework
- import_tasks: pluginmgr.yml
  when: (component == 'mano-framework') or
        (component == 'plugin-manager') or
        (component == 'all')

# ## Deploying Mano Components
# - import_tasks: finish_pm_cat_rep.yaml
#   when: (component == 'mano-framework') or
#         (component == 'placement-plugin') or
#         (component == 'all')

# deploy Service Lifecycle Manager of MANO framework
- import_tasks: slm.yml
  when: (component == 'mano-framework') or
        (component == 'slm') or
        (component == 'all')

# deploy Function Lifecycle Manager of MANO framework
- import_tasks: flm.yml
  when: (component == 'mano-framework') or
        (component == 'flm') or
        (component == 'all')

# deploy Specific Manager Registry of MANO framework
- import_tasks: smr.yml
  when: (component == 'mano-framework') or
        (component == 'smr') or
        (component == 'all')

# deploy Placement Plugin of MANO framework
- import_tasks: placementplugin.yml
  when: (component == 'mano-framework') or
        (component == 'placement-plugin') or
        (component == 'all')

- import_tasks: emu-wrapper.yml
  when: (component == 'mano-framework') or
        (component == 'placement-plugin') or
        (component == 'all')

# # deploy Placement Plugin of MANO framework
# - import_tasks: rabbitmq_plugins.yaml
#   when: (component == 'mano-framework') or
#         (component == 'placement-plugin') or
#         (component == 'all')

- import_tasks: finish_plugins.yaml
  when: (component == 'mano-framework') or
        (component == 'placement-plugin') or
        (component == 'all')

# # deploy mongo-express
# - import_tasks: mongo-express.yml
#   when: (target == 'pre-int-sp-ath.5gtango.eu') or
#         (target == 'int-sp-ath.5gtango.eu') or
#         (target == 'qual-sp-bcn.5gtango.eu') and
#         (component == 'all')
