---
# Rabbitmq Plugins
- name: Activating rabbitmq_management_visualiser Plugin
  shell: /usr/bin/docker exec -i son-broker rabbitmq-plugins enable rabbitmq_management_visualiser

- name: Activating rabbitmq_tracing Plugin
  shell: /usr/bin/docker exec -i son-broker rabbitmq-plugins enable rabbitmq_tracing